sudo: false
language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: ""
  on:
    tags: true
    all_branches: true
